name: Build JAR File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Archive JAR
        uses: actions/upload-artifact@v2
        with:
          name: my-jar
          path: build/libs/*.jar
